export enum PermissionLevel {
    FREE_PERMISSION = 1,
    PAID_PERMISSION = 2,
    ANOTHER_PAID_PERMISSION = 4,
    ADMIN_PERMISSION = 8,
    SUDO_PERMISSION = 2147483647,
}

export enum BO_ROLE {
    SUPER_ADMIN = "SUPER_ADMIN",
    MOD = "MOD",
    ADMIN = "ADMIN"
}

export enum BO_MODULE {
    PROJECT = "PROJECT",
    SECTION = "SECTION",
    PROJECT_POST = "PROJECT_POST",
    PROJECT_IMAGE = "PROJECT_IMAGE",
    FILE_LINK = "FILE_LINK",
    UTILITY="UTILITY",
    PROJECT_UTILITY="PROJECT_UTILITY",
    BO_USER="BO_USER",
    TRANSACTION="TRANSACTION"
}